import { cp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
// The repository root and dist use identical URLs. Both are ready to open.
await mkdir('public/vendor', { recursive: true });
const storage = (await readFile('src/storage.js', 'utf8')).replace(/^export /gm, '');
const main = (await readFile('src/main.js', 'utf8')).replace(/^import .*from '\.\/storage\.js';\s*/m, '');
await writeFile('public/game.js', '/* Generated by npm run build. Edit src/, then rebuild. */\n(() => {\n"use strict";\n' + storage + '\n' + main + '\n})();\n');
await cp('node_modules/phaser/dist/phaser.min.js', 'public/vendor/phaser.min.js');
await cp('node_modules/phaser/LICENSE.md', 'public/vendor/phaser-LICENSE.txt');
await rm('dist', { recursive: true, force: true });
await mkdir('dist/src', { recursive: true });
await Promise.all([
  cp('index.html', 'dist/index.html'), cp('src/style.css', 'dist/src/style.css'),
  cp('public', 'dist/public', { recursive: true }),
]);
console.log('Готово: index.html и dist/index.html запускаются без CDN и ES-модулей.');
