import { cp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
// The repository root and dist use identical URLs. Both are ready to open.
await mkdir('public/vendor', { recursive: true });
const storage = (await readFile('src/storage.js', 'utf8')).replace(/^export /gm, '');
const parts = await Promise.all(['src/collection-catalog.js','src/collection-state.js','src/artifact-catalog.js','src/artifact-state.js','src/artifact-art.js','src/collection-page.js','src/artifact-scene.js','src/building-blueprints.js','src/building-blueprint-scene.js','src/base-state.js','src/demyan-state.js','src/settlement-state.js','src/drill-motion.js','src/drive-controller.js','src/floor-prop-frames.js','src/materials.js','src/deposits.js','src/cargo-state.js','src/ground-cargo-state.js','src/rock-fragments.js','src/ground-cargo-scene.js','src/floor-clear-state.js','src/floor-clear-scene.js','src/cargo-scene.js','src/terrain.js','src/lift-state.js','src/lift-view.js','src/story-content.js','src/story-dialogue.js','src/porodnik-state.js','src/workshop-state.js','src/workshop-view.js','src/weapon-catalog.js','src/structure-recipes.js','src/recipe-presentation.js','src/structure-recipe-scene.js','src/recipe-drop-state.js','src/recipe-drop-scene.js','src/armory-state.js','src/weapon-panel.js','src/repair-state.js','src/tunnel-path.js','src/combat-state.js','src/people-view.js','src/repair-scene.js','src/combat-scene.js','src/armory-scene.js','src/construction-state.js','src/construction-scene.js','src/quest-item-view.js','src/quest-rewards.js','src/building-layout-state.js','src/editor-camera.js','src/building-layout-scene.js','src/demyan-scene.js','src/settlement-scene.js','src/discovery-banner.js','src/bonus-cache-state.js','src/bonus-cache-scene.js','src/base-scene.js','src/floor-scene.js','src/main.js'].map(path => readFile(path,'utf8')));
parts.unshift(await readFile('src/mounted-weapon.js','utf8'));
parts.unshift(await readFile('src/touch-joystick.js','utf8'));
parts.unshift(await readFile('src/viewport-sync.js','utf8'));
parts.push(await readFile('src/interface-panels.js','utf8'));
parts.splice(parts.length-2,0,await readFile('src/game-menus.js','utf8'));
parts.unshift(await readFile('src/drill-balance.js','utf8'));
const main = parts.map(source => source.replace(/^import .*;\s*$/gm, '').replace(/^export /gm,'')).join('\n');
await writeFile('public/game.js', '/* Generated by npm run build. Edit src/, then rebuild. */\n(() => {\n"use strict";\n' + storage + '\n' + main + '\n})();\n');
await cp('node_modules/phaser/dist/phaser.min.js', 'public/vendor/phaser.min.js');
await cp('node_modules/phaser/LICENSE.md', 'public/vendor/phaser-LICENSE.txt');
await rm('dist', { recursive: true, force: true });
await mkdir('dist/src', { recursive: true });
await Promise.all([
  cp('index.html', 'dist/index.html'), cp('src/style.css', 'dist/src/style.css'),
  cp('public', 'dist/public', { recursive: true }),
]);
console.log('Готово: index.html и dist/index.html запускаются без CDN и ES-модулей.');
