import { cp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
// The repository root and dist use identical URLs. Both are ready to open.
await mkdir('public/vendor', { recursive: true });
const storage = (await readFile('src/storage.js', 'utf8')).replace(/^export /gm, '');
const parts = await Promise.all(['src/base-state.js','src/drill-motion.js','src/drive-controller.js','src/floor-prop-frames.js','src/materials.js','src/deposits.js','src/cargo-state.js','src/cargo-scene.js','src/terrain.js','src/lift-state.js','src/lift-view.js','src/story-content.js','src/story-dialogue.js','src/porodnik-state.js','src/workshop-state.js','src/workshop-view.js','src/armory-state.js','src/repair-state.js','src/tunnel-path.js','src/combat-state.js','src/people-view.js','src/repair-scene.js','src/combat-scene.js','src/armory-scene.js','src/base-scene.js','src/floor-scene.js','src/main.js'].map(path => readFile(path,'utf8')));
parts.unshift(await readFile('src/mounted-weapon.js','utf8'));
parts.push(await readFile('src/interface-panels.js','utf8'));
const main = parts.map(source => source.replace(/^import .*;\s*$/gm, '').replace(/^export /gm,'')).join('\n');
await writeFile('public/game.js', '/* Generated by npm run build. Edit src/, then rebuild. */\n(() => {\n"use strict";\n' + storage + '\n' + main + '\n})();\n');
await cp('node_modules/phaser/dist/phaser.min.js', 'public/vendor/phaser.min.js');
await cp('node_modules/phaser/LICENSE.md', 'public/vendor/phaser-LICENSE.txt');
await rm('dist', { recursive: true, force: true });
await mkdir('dist/src', { recursive: true });
await Promise.all([
  cp('index.html', 'dist/index.html'), cp('src/style.css', 'dist/src/style.css'),
  cp('public', 'dist/public', { recursive: true }),
]);
console.log('Готово: index.html и dist/index.html запускаются без CDN и ES-модулей.');
