import { COLLECTIONS, COLLECTION_EFFECTS, RARITY_NAMES } from './collection-catalog.js';
import { ARTIFACTS } from './artifact-catalog.js';
import { collectionProgress, collectionBuffTotals, prepareCollectionClose } from './collection-state.js';
import { showGamePanel } from './game-menus.js';
import { writeSave } from './storage.js';
const artifactInfo=new Map(ARTIFACTS.map((a,i)=>[a.id,{...a,rarity:Math.floor(i/20)+1}]));
const effectLabels=Object.fromEntries(Object.entries(COLLECTION_EFFECTS).map(([label,key])=>[key,label]));
export const formatCollectionBuff=n=>'+'+(n*100).toLocaleString('ru-RU',{minimumFractionDigits:3,maximumFractionDigits:3})+'%';
export function createCollectionPage(scene){
 const root=document.createElement('section');root.className='collection-page';let tier=1,filter='all',query='',page=0,selected=null,confirming=false,showBuffs=!globalThis.window?.matchMedia?.('(max-height:420px) and (min-aspect-ratio:1/1)')?.matches;
 const summary=document.createElement('div');summary.className='collection-summary';
 const controls=document.createElement('div');controls.className='collection-filters';
 const search=document.createElement('input');search.type='search';search.placeholder='Коллекция или артефакт';search.setAttribute('aria-label','Поиск коллекций');
 const levels=document.createElement('select');levels.setAttribute('aria-label','Ступень коллекций');for(let i=1;i<=10;i++){const option=document.createElement('option');option.value=String(i);option.textContent=i+' · '+RARITY_NAMES[i-1];option.title='Коллекции '+((i-1)*100+1)+'–'+(i*100);levels.append(option);}
 const statuses=document.createElement('select');statuses.setAttribute('aria-label','Состояние коллекций');for(const [value,label] of [['all','Все коллекции'],['ready','Можно закрыть'],['partial','Начатые'],['done','Закрытые']]){const option=document.createElement('option');option.value=value;option.textContent=label;statuses.append(option);}
 controls.append(levels,statuses,search);
 const body=document.createElement('div');body.className='collection-list';const pager=document.createElement('div');pager.className='collection-pager';const note=document.createElement('p');note.className='collection-note';note.setAttribute('role','status');root.append(summary,controls,body,pager,note);
 const button=(text,action,cls='floor-button')=>{const b=document.createElement('button');b.type='button';b.className=cls;b.textContent=text;b.addEventListener('click',action);return b;};
 function render(){
  summary.replaceChildren();const progress=document.createElement('strong');progress.textContent='Закрыто '+scene.closedCollections.length+' / 1000';summary.append(progress);const toggle=button(showBuffs?'БАФЫ ▲':'БАФЫ ▾',()=>{showBuffs=!showBuffs;render();},'collection-buff-toggle');toggle.setAttribute('aria-expanded',String(showBuffs));summary.append(toggle);summary.classList.toggle('buffs-collapsed',!showBuffs);const buffs=collectionBuffTotals(scene.closedCollections);for(const [key,label] of Object.entries(effectLabels)){const value=document.createElement('span');value.textContent=label+': '+formatCollectionBuff(buffs[key]);summary.append(value);}
  body.replaceChildren();pager.replaceChildren();controls.hidden=!!selected;body.classList.toggle('collection-details',!!selected);
  if(selected){
   const c=selected,state=collectionProgress(c,scene.artifacts,scene.closedCollections),title=document.createElement('h3');title.textContent='№'+c.id+' · '+c.name;body.append(title);const reward=document.createElement('p');reward.className='collection-reward';reward.textContent=effectLabels[c.effect]+' '+formatCollectionBuff(c.buff)+(state.done?' · действует постоянно':' · после полного закрытия');body.append(reward);
   for(const id of c.artifacts){const a=artifactInfo.get(id),row=document.createElement('div');row.className='collection-item';const label=document.createElement('span'),owned=document.createElement('strong');label.textContent=a.name+' · '+RARITY_NAMES[a.rarity-1]+' · этаж '+a.floor;owned.textContent=state.done?'Зачтён':(scene.artifacts[id]||0)+' в запасе / нужно 1';row.classList.toggle('missing',!state.done&&!(scene.artifacts[id]>0));row.append(label,owned);body.append(row);}
   const warning=document.createElement('p');warning.className='collection-warning';warning.textContent=state.done?'Артефакты израсходованы при закрытии. Награда сохранена. Повторное закрытие недоступно.':'Весь состав будет израсходован. Для других коллекций эти артефакты придётся найти снова. До закрытия эта коллекция даёт ноль.';body.append(warning);
   if(confirming){const affected=COLLECTIONS.filter(other=>other.id!==c.id&&!scene.closedCollections.includes(other.id)&&other.artifacts.some(id=>c.artifacts.includes(id))).length;warning.textContent+=' Общие артефакты нужны ещё в '+affected+' незакрытых коллекциях.';const confirm=button('ПОДТВЕРДИТЬ ЗАКРЫТИЕ',()=>{const result=scene.closeCollection(c.id);if(!result){note.textContent='Не удалось закрыть: проверь состав и доступность сохранения.';confirming=false;render();return;}note.textContent='Коллекция закрыта. '+effectLabels[c.effect]+' '+formatCollectionBuff(c.buff);confirming=false;render();},'metal-button');body.append(confirm,button('ОТМЕНА',()=>{confirming=false;render();}));}
   else if(!state.done){const close=button('ЗАКРЫТЬ КОЛЛЕКЦИЮ',()=>{confirming=true;render();},'metal-button');close.disabled=!state.ready;body.append(close);if(!state.ready){const missing=document.createElement('p');missing.textContent='Собрано '+state.found+' из '+state.total+'. Баф этой коллекции: 0%.';body.append(missing);}}
   body.append(button('← К СПИСКУ',()=>{selected=null;confirming=false;note.textContent='';render();}));return;
  }
  const rows=COLLECTIONS.filter(c=>{if(c.tier!==tier)return false;const s=collectionProgress(c,scene.artifacts,scene.closedCollections);if(filter==='ready'&&!s.ready||filter==='done'&&!s.done||filter==='partial'&&(s.done||!s.found))return false;return !query||(c.id+' '+c.name+' '+c.artifacts.map(id=>artifactInfo.get(id).name).join(' ')).toLocaleLowerCase('ru-RU').includes(query);});
  page=Math.min(page,Math.max(0,Math.ceil(rows.length/20)-1));for(const c of rows.slice(page*20,page*20+20)){const s=collectionProgress(c,scene.artifacts,scene.closedCollections),card=button('',()=>{selected=c;note.textContent='';render();},'collection-card');card.classList.toggle('completed',s.done);card.classList.toggle('ready',s.ready);const name=document.createElement('strong'),reward=document.createElement('span'),status=document.createElement('small');name.textContent='№'+c.id+' · '+c.name;reward.textContent=effectLabels[c.effect]+' '+formatCollectionBuff(c.buff);status.textContent=s.done?'ЗАКРЫТА · БАФ ДЕЙСТВУЕТ':s.ready?'НАБОР СОБРАН · МОЖНО ЗАКРЫТЬ':'Собрано '+s.found+' / '+s.total+' · баф 0%';card.append(name,reward,status);body.append(card);}
  if(!rows.length){const empty=document.createElement('p');empty.textContent='Коллекций с такими условиями нет. Выбери другую ступень или фильтр.';body.append(empty);}
  const prev=button('← НАЗАД',()=>{page--;render();}),next=button('ВПЕРЁД →',()=>{page++;render();}),label=document.createElement('span');prev.disabled=page===0;next.disabled=(page+1)*20>=rows.length;label.textContent=(page+1)+' / '+Math.max(1,Math.ceil(rows.length/20))+' · найдено '+rows.length;pager.append(prev,label,next);note.textContent='Закрытие — по подтверждению. Предметы сами не расходуются.';
 }
 search.addEventListener('input',()=>{query=search.value.trim().toLocaleLowerCase('ru-RU');page=0;render();});levels.addEventListener('change',()=>{tier=Number(levels.value);page=0;render();});statuses.addEventListener('change',()=>{filter=statuses.value;page=0;render();});const media=globalThis.window?.matchMedia?.('(max-height:420px) and (min-aspect-ratio:1/1)');const compactChange=()=>{showBuffs=!media.matches;render();};media?.addEventListener?.('change',compactChange);document.querySelector('#dialog')?.addEventListener('close',()=>media?.removeEventListener?.('change',compactChange),{once:true});render();return root;
}
export const collectionMethods={
 cargoCapacity(){return Math.floor(200*(1+(this.collectionBuffs?.cargo||0))+1e-8);},
 closeCollection(id){const next=prepareCollectionClose(id,this.artifacts,this.closedCollections);if(!next)return false;const progress={...this.snapshotCampaign(),artifacts:next.artifacts,closedCollections:next.closedCollections};if(!writeSave(progress))return false;this.artifacts=next.artifacts;this.closedCollections=next.closedCollections;this.collectionBuffs=collectionBuffTotals(this.closedCollections);this.campaign=progress;this.refreshHUD();return true;},
 openCollections(back=null){if(this.layoutEditing||this.busy||this.storyActive)return;this.dialogClosed();this.persist();showGamePanel('КОЛЛЕКЦИИ',createCollectionPage(this),'collections',back);}
};
